### PR TITLE
Euro

### PR DESCRIPTION
**Pull request by graffic**
EuroPython blog changes (Sorry for the title, I pressed enter by mistake while typing).

Need help with anything? Add a comment to the pull request.

This will week I'll be in _whip me_ mode (whip me to get me to work on something). Next week I'll be in _beach mode_ (I might not find time to help, but I'll answer with a picture from the beach) :smile_cat:

### CODE REVIEW

**Comment by pelme** [comment]
**Very** nice, thanks a lot for this!

Ok, so here comes a whip list from me playing around with it a bit:
- Is it really necessary to create the output dir first time? Otherwise we should just make it part of the Makefile. It would be really nice to lower the number of steps to contribute where possible. :)
- Document how to stop devserver (make stopserver)
- Feeds would be nice, they does not seem to be activated now(?)
- rsync/upload command as part of Makefile to upload to server (i.e. make upload) or something like that. We can probably put this in when we actually fix things up for the real server. Pelican has an rsync_upload command that is ripped out currently, should be easy to add back. 

We would need an introductionary post that describes the intent of the blog (to get contributions from the community and to post announcements on new releases etc) and to show off some short examples of how to use the blog markdown to provide code samples etc. I can start to draft a post like that!

We could probably build+post it to some server and try to collect some quick feedback from others during the week and then just put it on pytest.org.

This is going to be awesome! :boom:

**Comment by ionelmc** [comment]
Quick question: don't you plan to use GitHub Pages for serving the blog?

You can use Travis to do building/publishing for you (I've done it [here](https://github.com/RoPython/ropython-site/blob/master/.travis.yml) for another community-run blog) - I can help you get it set up here if you want.

**Comment by pelme** [comment]
@ionelmc Cool idea! We planned to keep it simple and run it on pytest.org/blog (just rsync the output dir there). Using Travis to have automatic builds would be super nice, but it should basically be the same amount of work I guess? :)

**Comment by ionelmc** [comment]
Well the idea was that people who want to write/change some content don't need to have python and tox installed locally. Eg: you'd be able to fix typos and such from your phone. Just edit via GitHub UI

**Comment by pelme** [comment]
Yes, that would be very nice indeed. I mean that it should be possible to rsync instead of pushing to github pages. I.e. you still need to manage the encrypted ssh keys in Travis, so the setup would be the same as in the ropython project, but the final step would be rsync instead of a push to github pages. We could also just use blog.pytest.org and use github pages and avoid using the pytest.org server at all.

**Comment by ionelmc** [comment]
For authentication in Travis I've used [ssh keys](http://blog.ionelmc.ro/2015/07/11/publishing-to-github-pages-from-travis-ci/) - I suspect the same technique can be applied to rsync publishing.

I'm not saying you should use GitHub pages, I was just asking.

**Comment by pelme** [comment]
It's not yet fully decided I guess, the most important is to get something going, so I guess we should just go for the easiest approach. Since you already have everything setup with github pages, we should probably do that :)

Anything that lowers the barrier for contributions to the blog is very welcome, having the blog be built automatically from PR:s is very nice.

**Comment by pfctdayelise** [comment]
Was getting build errors, I just figured out that `webassets` is missing from requirements.txt.

**Comment by pfctdayelise** [comment]
pytestblog
I'm guessing the output should look a little more exciting than this?

**Comment by pelme** [comment]
I merged this and created separate issues for the bits I've found here

**Comment by graffic** [comment]
ok!

On Mon, Aug 31, 2015 at 11:10 PM, Andreas Pelme notifications@github.com
wrote:

> I merged this and created separate issues for the bits I've found here
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pytest-dev/blog.pytest.org/pull/1#issuecomment-136485827
> .

## 

Javier Gonel
Senior Software Engineer
http://javier.gr/
PGP: 0x53D69D57

**Pull request merged**
